"""Law domain profile — legal lectures, case discussions, statutory analysis."""

from __future__ import annotations

from pathlib import Path

from .base import fmt_time

_PROMPTS = Path(__file__).parent.parent / "llm" / "prompts" / "domains"

_DISCLAIMER = (
    "> **DISCLAIMER:** Not legal advice. "
    "Generated by AI; verify all citations independently.\n\n"
)


class LawProfile:
    name = "law"
    description = "Legal lectures, case discussions, and statutory analysis."

    def chunk_prompt_addendum(self) -> str:
        return (_PROMPTS / "law.txt").read_text(encoding="utf-8")

    def global_prompt_addendum(self) -> str:
        return ""

    def extra_output_schema(self) -> dict | None:
        return None

    def post_process(self, summary: dict, fused: dict, output_dir: Path) -> list[Path]:
        """Prepend disclaimer to summary.md and write case_brief.md."""
        created: list[Path] = []
        extras = {**summary, **summary.get("domain_extras", {})}

        # Prepend disclaimer to summary.md
        md_path = output_dir / "summary.md"
        if md_path.exists():
            original = md_path.read_text(encoding="utf-8")
            md_path.write_text(_DISCLAIMER + original, encoding="utf-8")

        # Write case_brief.md (IRAC format where applicable)
        lines: list[str] = [_DISCLAIMER, "# Case Brief\n"]

        cases = extras.get("cases_cited", [])
        if cases:
            lines.append("## Cases Cited\n")
            for c in cases:
                if not isinstance(c, dict):
                    lines.append(f"- {c}")
                    continue
                ts = fmt_time(float(c.get("timestamp", 0)))
                citation = c.get("citation", "")
                jurisdiction = c.get("jurisdiction", "")
                relevance = c.get("relevance", "")
                meta = ", ".join(filter(None, [citation, jurisdiction]))
                lines.append(
                    f"- [{ts}] **{c.get('case_name', '')}**"
                    + (f" — {meta}" if meta else "")
                    + (f": {relevance}" if relevance else "")
                )
            lines.append("")

        statutes = extras.get("statutes", [])
        if statutes:
            lines.append("## Statutes Referenced\n")
            for s in statutes:
                if not isinstance(s, dict):
                    lines.append(f"- {s}")
                    continue
                ts = fmt_time(float(s.get("timestamp", 0)))
                section = s.get("section", "")
                lines.append(
                    f"- [{ts}] {s.get('name', '')}"
                    + (f" § {section}" if section else "")
                )
            lines.append("")

        principles = extras.get("legal_principles", [])
        if principles:
            lines.append("## Legal Principles\n")
            for p in principles:
                if not isinstance(p, dict):
                    lines.append(f"- {p}")
                    continue
                ts = fmt_time(float(p.get("timestamp", 0)))
                lines.append(
                    f"- [{ts}] **{p.get('doctrine', '')}**: {p.get('explanation', '')}"
                )
            lines.append("")

        arguments = extras.get("arguments", [])
        if arguments:
            lines.append("## Arguments\n")
            for a in arguments:
                if not isinstance(a, dict):
                    lines.append(f"- {a}")
                    continue
                ts = fmt_time(float(a.get("timestamp", 0)))
                position = a.get("position", "").upper()
                lines.append(f"- [{ts}] [{position}] {a.get('statement', '')}")
            lines.append("")

        brief_path = output_dir / "case_brief.md"
        brief_path.write_text("\n".join(lines), encoding="utf-8")
        created.append(brief_path)
        return created
