"""Trading domain profile — financial markets, signals, technical analysis."""

from __future__ import annotations

import csv
from pathlib import Path

from .base import fmt_time

_PROMPTS = Path(__file__).parent.parent / "llm" / "prompts" / "domains"

_DISCLAIMER = (
    "> **DISCLAIMER:** This summary is generated by AI for informational purposes only "
    "and is **not financial advice**. Always conduct your own research.\n\n"
)


class TradingProfile:
    name = "trading"
    description = "Financial markets, trading signals, and technical analysis."

    def chunk_prompt_addendum(self) -> str:
        return (_PROMPTS / "trading.txt").read_text(encoding="utf-8")

    def global_prompt_addendum(self) -> str:
        return ""

    def extra_output_schema(self) -> dict | None:
        return {
            "tickers_mentioned": {"type": "array", "items": {"type": "string"}},
            "signals": {"type": "array"},
            "indicators": {"type": "array"},
            "risk_warnings": {"type": "array", "items": {"type": "string"}},
        }

    def post_process(self, summary: dict, fused: dict, output_dir: Path) -> list[Path]:
        """Prepend disclaimer to summary.md and write trade_log.csv."""
        created: list[Path] = []
        extras = {**summary, **summary.get("domain_extras", {})}

        # Prepend disclaimer to summary.md
        md_path = output_dir / "summary.md"
        if md_path.exists():
            original = md_path.read_text(encoding="utf-8")
            md_path.write_text(_DISCLAIMER + original, encoding="utf-8")

        # Write trade_log.csv
        signals = extras.get("signals", [])
        if signals:
            csv_path = output_dir / "trade_log.csv"
            with csv_path.open("w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(
                    f,
                    fieldnames=["timestamp", "ticker", "action", "rationale", "timeframe"],
                )
                writer.writeheader()
                for sig in signals:
                    if not isinstance(sig, dict):
                        continue
                    writer.writerow({
                        "timestamp": fmt_time(float(sig.get("timestamp", 0))),
                        "ticker": sig.get("ticker", ""),
                        "action": sig.get("action", ""),
                        "rationale": sig.get("rationale", ""),
                        "timeframe": sig.get("timeframe", ""),
                    })
            created.append(csv_path)

        return created
