"""HTML report renderer."""

import re
from pathlib import Path

try:
    import markdown
    MARKDOWN_AVAILABLE = True
except ImportError:
    MARKDOWN_AVAILABLE = False

from .helpers import to_data_uri, escape_html


def get_report_css() -> str:
    """Load report CSS."""
    css_path = Path(__file__).parent / "templates" / "report.css"
    if css_path.exists():
        return css_path.read_text()
    return ""


def embed_images_in_html(html_content: str, output_dir: Path, embed_images: bool = True, max_width: int = 480) -> str:
    """
    Replace image references with data URIs or adjust paths.

    Args:
        html_content: HTML content with <img> tags
        output_dir: Output directory for relative paths
        embed_images: If True, convert to data URIs; else keep relative paths
        max_width: Max width for embedded images

    Returns:
        Modified HTML content
    """
    if not embed_images:
        # Just adjust paths to be relative to output_dir
        # This is already done in markdown renderer, so return as-is
        return html_content

    # Find all img tags and convert src attributes to data URIs
    def replace_img_src(match):
        tag = match.group(0)
        src_match = re.search(r'src="([^"]*)"', tag)
        if not src_match:
            return tag

        src = src_match.group(1)
        # Skip if already data URI
        if src.startswith("data:"):
            return tag

        # Try to find the file
        frame_path = output_dir.parent / src if output_dir.name else Path(src)
        if frame_path.exists():
            try:
                data_uri = to_data_uri(frame_path, max_width)
                return tag.replace(f'src="{src}"', f'src="{data_uri}"')
            except Exception:
                # If conversion fails, keep original
                return tag

        return tag

    # Replace img src attributes
    html_content = re.sub(r'<img\b[^>]*>', replace_img_src, html_content)
    return html_content


def render_html(
    markdown_content: str,
    output_dir: Path,
    embed_images: bool = True,
    max_width: int = 480,
    run_id: str = "",
) -> str:
    """
    Render complete HTML report.

    Args:
        markdown_content: Markdown content to convert
        output_dir: Output directory (for image path resolution)
        embed_images: If True, embed images as data URIs
        max_width: Max width for embedded images
        run_id: Run ID for title

    Returns:
        Complete HTML string
    """
    # Convert markdown to HTML
    if MARKDOWN_AVAILABLE:
        extensions = [
            "tables",
            "fenced_code",
            "nl2br",
        ]
        html_body = markdown.markdown(markdown_content, extensions=extensions)
    else:
        # Fallback: basic HTML conversion
        html_body = "<pre>" + escape_html(markdown_content) + "</pre>"

    # Embed images if requested
    html_body = embed_images_in_html(html_body, output_dir, embed_images, max_width)

    # Get CSS
    css = get_report_css()

    # Build complete HTML document
    title = f"Summary: Run {run_id}" if run_id else "Summary Report"

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escape_html(title)}</title>
    <style>
{css}
    </style>
</head>
<body>
{html_body}
<footer>
    <p>Generated by DIP Video Understanding System</p>
</footer>
</body>
</html>"""

    return html_doc
